# Generated by Django 5.0 on 2024-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examinee',
            fields=[
                ('exam_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('birthday', models.CharField(blank=True, default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.CharField(max_length=33, primary_key=True, serialize=False)),
                ('exam_number', models.CharField(blank=True, default='', max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('birthday', models.CharField(blank=True, default='', max_length=8)),
                ('question', models.TextField(blank=True, default='')),
            ],
        ),
    ]
